/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseui;

/**
 *
 * @author Landon Creel
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TypeSelectRadio = new javax.swing.ButtonGroup();
        commandSelect = new javax.swing.JTabbedPane();
        basicSearchPanel = new javax.swing.JPanel();
        personBasicRadio = new javax.swing.JRadioButton();
        entryBasicLabel = new javax.swing.JLabel();
        movieBasicRadio = new javax.swing.JRadioButton();
        nameBasicLabel = new javax.swing.JLabel();
        nameBasicField = new javax.swing.JTextField();
        displayBasic = new javax.swing.JTabbedPane();
        peopleBasic = new javax.swing.JPanel();
        peopleBasicPanel = new javax.swing.JScrollPane();
        peopleBasicOutput = new javax.swing.JTextPane();
        moviesBasic = new javax.swing.JPanel();
        movieBasicPanel = new javax.swing.JScrollPane();
        movieBasicOutput = new javax.swing.JTextPane();
        writeBasic = new javax.swing.JButton();
        searchBasic = new javax.swing.JButton();
        fileNameBasicField = new javax.swing.JTextField();
        ageYearBasicLabel = new javax.swing.JLabel();
        ageYearBasicSpinner = new javax.swing.JSpinner();
        advancedSearchPanel = new javax.swing.JPanel();
        writeAdvanced = new javax.swing.JButton();
        nameAdvancedField = new javax.swing.JTextField();
        fileNameAdvancedField = new javax.swing.JTextField();
        ageYearAdvancedSpinner = new javax.swing.JSpinner();
        nameAdvancedLabel = new javax.swing.JLabel();
        searchAdvanced = new javax.swing.JButton();
        displayAdvanced = new javax.swing.JTabbedPane();
        peopleBasic2 = new javax.swing.JPanel();
        peopleBasicPanel2 = new javax.swing.JScrollPane();
        peopleBasicOutput2 = new javax.swing.JTextPane();
        moviesBasic2 = new javax.swing.JPanel();
        movieBasicPanel2 = new javax.swing.JScrollPane();
        movieBasicOutput2 = new javax.swing.JTextPane();
        personAdvancedRadio = new javax.swing.JRadioButton();
        entryAdvancedLabel = new javax.swing.JLabel();
        ageYearAdvancedLabel = new javax.swing.JLabel();
        movieAdvancedRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Database");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        TypeSelectRadio.add(personBasicRadio);
        personBasicRadio.setText("Person");
        personBasicRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personBasicRadioActionPerformed(evt);
            }
        });

        entryBasicLabel.setText("Entry Type");

        TypeSelectRadio.add(movieBasicRadio);
        movieBasicRadio.setText("Movie");

        nameBasicLabel.setText("Name");

        nameBasicField.setText("Enter name here...");

        peopleBasicPanel.setViewportView(peopleBasicOutput);

        javax.swing.GroupLayout peopleBasicLayout = new javax.swing.GroupLayout(peopleBasic);
        peopleBasic.setLayout(peopleBasicLayout);
        peopleBasicLayout.setHorizontalGroup(
            peopleBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
            .addGroup(peopleBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peopleBasicLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(peopleBasicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        peopleBasicLayout.setVerticalGroup(
            peopleBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
            .addGroup(peopleBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peopleBasicLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(peopleBasicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        displayBasic.addTab("People", peopleBasic);

        movieBasicPanel.setViewportView(movieBasicOutput);

        javax.swing.GroupLayout moviesBasicLayout = new javax.swing.GroupLayout(moviesBasic);
        moviesBasic.setLayout(moviesBasicLayout);
        moviesBasicLayout.setHorizontalGroup(
            moviesBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
            .addGroup(moviesBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moviesBasicLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(movieBasicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        moviesBasicLayout.setVerticalGroup(
            moviesBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
            .addGroup(moviesBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moviesBasicLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(movieBasicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        displayBasic.addTab("Movies", moviesBasic);

        writeBasic.setText("Write Results to File");

        searchBasic.setText("Search");

        fileNameBasicField.setText("Enter file name here...");
        fileNameBasicField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameBasicFieldActionPerformed(evt);
            }
        });

        ageYearBasicLabel.setText("Age/Year");

        javax.swing.GroupLayout basicSearchPanelLayout = new javax.swing.GroupLayout(basicSearchPanel);
        basicSearchPanel.setLayout(basicSearchPanelLayout);
        basicSearchPanelLayout.setHorizontalGroup(
            basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, basicSearchPanelLayout.createSequentialGroup()
                        .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageYearBasicLabel)
                            .addComponent(nameBasicLabel)
                            .addComponent(nameBasicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movieBasicRadio)
                            .addComponent(personBasicRadio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(basicSearchPanelLayout.createSequentialGroup()
                        .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayBasic, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, basicSearchPanelLayout.createSequentialGroup()
                                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(entryBasicLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, basicSearchPanelLayout.createSequentialGroup()
                                        .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(searchBasic)
                                            .addComponent(ageYearBasicSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(399, 399, 399)
                                        .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(writeBasic, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fileNameBasicField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        basicSearchPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fileNameBasicField, writeBasic});

        basicSearchPanelLayout.setVerticalGroup(
            basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicSearchPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(entryBasicLabel)
                .addGap(17, 17, 17)
                .addComponent(personBasicRadio)
                .addGap(19, 19, 19)
                .addComponent(movieBasicRadio)
                .addGap(24, 24, 24)
                .addComponent(nameBasicLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameBasicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(ageYearBasicLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicSearchPanelLayout.createSequentialGroup()
                        .addComponent(fileNameBasicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicSearchPanelLayout.createSequentialGroup()
                        .addComponent(ageYearBasicSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(writeBasic)
                    .addComponent(searchBasic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayBasic, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        commandSelect.addTab("Basic Search", basicSearchPanel);

        writeAdvanced.setText("Write Results to File");

        nameAdvancedField.setText("Enter name here...");

        fileNameAdvancedField.setText("Enter file name here...");
        fileNameAdvancedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameAdvancedFieldActionPerformed(evt);
            }
        });

        nameAdvancedLabel.setText("Name");

        searchAdvanced.setText("Search");

        peopleBasicPanel2.setViewportView(peopleBasicOutput2);

        javax.swing.GroupLayout peopleBasic2Layout = new javax.swing.GroupLayout(peopleBasic2);
        peopleBasic2.setLayout(peopleBasic2Layout);
        peopleBasic2Layout.setHorizontalGroup(
            peopleBasic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
            .addGroup(peopleBasic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peopleBasic2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(peopleBasicPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        peopleBasic2Layout.setVerticalGroup(
            peopleBasic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
            .addGroup(peopleBasic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peopleBasic2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(peopleBasicPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        displayAdvanced.addTab("People", peopleBasic2);

        movieBasicPanel2.setViewportView(movieBasicOutput2);

        javax.swing.GroupLayout moviesBasic2Layout = new javax.swing.GroupLayout(moviesBasic2);
        moviesBasic2.setLayout(moviesBasic2Layout);
        moviesBasic2Layout.setHorizontalGroup(
            moviesBasic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
            .addGroup(moviesBasic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moviesBasic2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(movieBasicPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        moviesBasic2Layout.setVerticalGroup(
            moviesBasic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
            .addGroup(moviesBasic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moviesBasic2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(movieBasicPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        displayAdvanced.addTab("Movies", moviesBasic2);

        TypeSelectRadio.add(personAdvancedRadio);
        personAdvancedRadio.setText("Person");
        personAdvancedRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personAdvancedRadioActionPerformed(evt);
            }
        });

        entryAdvancedLabel.setText("Entry Type");

        ageYearAdvancedLabel.setText("Age/Year");

        TypeSelectRadio.add(movieAdvancedRadio);
        movieAdvancedRadio.setText("Movie");

        jLabel1.setText("Advanced Parameters");

        jLabel2.setText("Variable Type");

        jLabel3.setText("Condition");

        jTextField1.setText("value...");

        jLabel6.setText("Comparable");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Age", "Year", "Name", "Genre" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<", ">", "==", "!=", "<=", ">=" }));

        javax.swing.GroupLayout advancedSearchPanelLayout = new javax.swing.GroupLayout(advancedSearchPanel);
        advancedSearchPanel.setLayout(advancedSearchPanelLayout);
        advancedSearchPanelLayout.setHorizontalGroup(
            advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                        .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                                .addComponent(entryAdvancedLabel)
                                .addGap(430, 430, 430)
                                .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                                        .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))))
                            .addComponent(searchAdvanced)
                            .addComponent(ageYearAdvancedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageYearAdvancedLabel)
                            .addComponent(nameAdvancedLabel)
                            .addComponent(nameAdvancedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                                .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movieAdvancedRadio)
                                    .addComponent(personAdvancedRadio))
                                .addGap(430, 430, 430)
                                .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(writeAdvanced, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fileNameAdvancedField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(displayAdvanced))
                .addContainerGap())
        );
        advancedSearchPanelLayout.setVerticalGroup(
            advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(entryAdvancedLabel)
                        .addGap(17, 17, 17)
                        .addComponent(personAdvancedRadio)
                        .addGap(19, 19, 19)
                        .addComponent(movieAdvancedRadio)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advancedSearchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, advancedSearchPanelLayout.createSequentialGroup()
                                .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addComponent(nameAdvancedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameAdvancedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(ageYearAdvancedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advancedSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                        .addComponent(ageYearAdvancedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(searchAdvanced))
                    .addGroup(advancedSearchPanelLayout.createSequentialGroup()
                        .addComponent(fileNameAdvancedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(writeAdvanced)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayAdvanced, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        commandSelect.addTab("Advanced Search", advancedSearchPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1159, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(commandSelect, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 966, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(commandSelect, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void personBasicRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personBasicRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personBasicRadioActionPerformed

    private void fileNameBasicFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameBasicFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameBasicFieldActionPerformed

    private void fileNameAdvancedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameAdvancedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameAdvancedFieldActionPerformed

    private void personAdvancedRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personAdvancedRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personAdvancedRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TypeSelectRadio;
    private javax.swing.JPanel advancedSearchPanel;
    private javax.swing.JLabel ageYearAdvancedLabel;
    private javax.swing.JSpinner ageYearAdvancedSpinner;
    private javax.swing.JLabel ageYearBasicLabel;
    private javax.swing.JSpinner ageYearBasicSpinner;
    private javax.swing.JPanel basicSearchPanel;
    private javax.swing.JTabbedPane commandSelect;
    private javax.swing.JTabbedPane displayAdvanced;
    private javax.swing.JTabbedPane displayBasic;
    private javax.swing.JLabel entryAdvancedLabel;
    private javax.swing.JLabel entryBasicLabel;
    private javax.swing.JTextField fileNameAdvancedField;
    private javax.swing.JTextField fileNameBasicField;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton movieAdvancedRadio;
    private javax.swing.JTextPane movieBasicOutput;
    private javax.swing.JTextPane movieBasicOutput2;
    private javax.swing.JScrollPane movieBasicPanel;
    private javax.swing.JScrollPane movieBasicPanel2;
    private javax.swing.JRadioButton movieBasicRadio;
    private javax.swing.JPanel moviesBasic;
    private javax.swing.JPanel moviesBasic2;
    private javax.swing.JTextField nameAdvancedField;
    private javax.swing.JLabel nameAdvancedLabel;
    private javax.swing.JTextField nameBasicField;
    private javax.swing.JLabel nameBasicLabel;
    private javax.swing.JPanel peopleBasic;
    private javax.swing.JPanel peopleBasic2;
    private javax.swing.JTextPane peopleBasicOutput;
    private javax.swing.JTextPane peopleBasicOutput2;
    private javax.swing.JScrollPane peopleBasicPanel;
    private javax.swing.JScrollPane peopleBasicPanel2;
    private javax.swing.JRadioButton personAdvancedRadio;
    private javax.swing.JRadioButton personBasicRadio;
    private javax.swing.JButton searchAdvanced;
    private javax.swing.JButton searchBasic;
    private javax.swing.JButton writeAdvanced;
    private javax.swing.JButton writeBasic;
    // End of variables declaration//GEN-END:variables
}
